version: '3.8'

services:
  # 1. DATABASE POSTGRESQL + POSTGIS
  postgres:
    image: postgis/postgis:15-3.3
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./BE/UserAPI.sql:/docker-entrypoint-initdb.d/init.sql
      - ./BE/postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - my-shared-network

  # 2. USER MICROSERVICE (BE)
  user-api:
    container_name: user-api
    build:
      context: ./BE
      dockerfile: UserAPI/Dockerfile
    ports:
      - "${USER_API_PORT:-8081}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - Jwt__Key=${JWT_SECRET_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Cloudinary__CloudName=${CLOUDINARY_CLOUD_NAME}
      - Cloudinary__ApiKey=${CLOUDINARY_API_KEY}
      - Cloudinary__ApiSecret=${CLOUDINARY_API_SECRET}
    depends_on:
      - postgres
    networks:
      - my-shared-network

  # 2.5 RADAR MICROSERVICE (BE)
  radar-api:
    container_name: radar-api
    build:
      context: ./BE
      dockerfile: RadarAPI/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=radardb;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - Jwt__Key=${JWT_SECRET_KEY:-THIS_IS_SECRET_KEY_AT_LEAST_32_CHAR_LONG_123456}
      - Jwt__Issuer=${JWT_ISSUER:-LinkedLearnGateway}
      - Jwt__Audience=${JWT_AUDIENCE:-LinkedLearnClients}
    depends_on:
      - postgres
    networks:
      - my-shared-network

  # 3. API GATEWAY (OCELOT)
  gateway-api:
    container_name: gateway-api
    build:
      context: ./GateWay
      dockerfile: GateWay/Dockerfile
    ports:
      - "${GATEWAY_PORT:-5000}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - Jwt__Key=${JWT_SECRET_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
    depends_on:
      - user-api
    networks:
      - my-shared-network

  # 4. FRONTEND (LINKEDLEARN)
  frontend:
    container_name: frontend-app
    build:
      context: ./FE
      dockerfile: LinkedLearn/Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    depends_on:
      - gateway-api
    networks:
      - my-shared-network

networks:
  my-shared-network:
    driver: bridge
